### ISSUE TITLE
guard-haml-coffee not working

### ISSUE THREAD

**Issue by tommybstitch** [netzpirat/haml-coffee#108]
I know that there is a separate repository for the guard-haml-coffee plugin, but it seems pretty dead and no-one is responding to my issue on there. Whenever I try to guard init with guard-haml-coffee plugin installed, it fails on that plugin and I get the following error:

    $ ERROR - Could not load 'guard/haml-coffee' or '~/.guard/templates/haml-coffee' or find class Guard::Hamlcoffee
    $ERROR - Error is: No such file or directory - /Users/tommybstitch/.guard/templates/haml-coffee

Does anyone know how to fix this?

**Comment by vendethiel** [comment]
That's the guard ruby coffee thing, uh 
? Maybe a guard update broke some stuff?

**Comment by tommybstitch** [comment]
The manager of the Guard repository has actually helped me out here. The guard haml-coffee plugin was abandoned 3 years ago, but the manager of Guard has kindly updated the gem in a fork and made it work with new versions of Guard.

https://github.com/guard/guard-haml-coffee/tree/major_project_update

**Comment by vendethiel** [comment]
Amazing! Props to them :-)
