### ISSUE TITLE
Security Contact Needed

### ISSUE THREAD

**Issue by agustingianni** [netzpirat/haml-coffee#116]
Hello,

I am a member of the GitHub Security Lab (https://securitylab.github.com).

I've attempted to reach a maintainer for this project to report a potential security issue but have been unable to verify the report was received. Please could a project maintainer contact us at securitylab@github.com, or provide an email address so we can contact you.

Thank you,
Agustin Gianni (@agustingianni)
GitHub Security Lab

**Comment by vendethiel** [comment]
Hi,

See #97. There's not really a dedicated maintainer to this repo, though there are several people here that do try to look at PRs.

**Comment by agustingianni** [comment]
Oh, I see, that's very sad to hear :(

Is there any way to contact some of the people in that thread via email to send them a security advisory?

Thanks for the response.
