### ISSUE TITLE
Attention: @netzpirat passed away in April '14

### ISSUE THREAD

**Issue by janv** [netzpirat/haml-coffee#97]
I, together with @sebastiandeutsch were the first committers on the project, before handing it over to Michael (@netzpirat).

I have just learned that Michael has [passed away in the beginning of April](https://groups.google.com/forum/?utm_source=rubyweekly&utm_medium=email#!msg/guard-dev/2Td0QTvTIsE/cegvVofIJ8AJ). I'm putting up this issue to bring this to the attention of HAML-Coffee users.

This also means that haml-coffee needs a new maintainer. Unfortunately my free time doesn't allow for maintenance of this project in the extent Michael worked on HAML-Coffee.

:(

**Comment by effkay** [comment]
Guys, any news on who would take over the role of maintainer here? I will be transferring repositories to my account this weekend so at least I get notifications of new Issues and may be able to help out a bit more, but I am not actively using haml-coffee so I might not be the best fit here.. @sebastiandeutsch @janv?

**Comment by scottbrady** [comment]
My company has migrated from haml-coffee to Jade because of uncertainty around the project's future. This is still a great module; it would be great to see someone pick up development.

**Comment by vendethiel** [comment]
I havn't done any JS-related for almost a year now, and I use jade as well :).

**Comment by janv** [comment]
Sorry, but I'm also not a good fit

**Comment by vendethiel** [comment]
Does someone know what would be the procedure to publish a npm right? It seems Michael didn’t have other collaborators on the package

**Comment by janv** [comment]
I am cleaning up my open issues.
Since this issue is now many years old, I think it served its purpose and I'll close it.
